[env.shellopts]
LESS = "-FRM"
LESSHISTFILE = "$XDG_STATE_HOME/less/history"
SQLITE_HISTORY = "$XDG_STATE_HOME/sqlite_history"
INPUTRC = "$XDG_CONFIG_HOME/readline/inputrc" # TODO: file still needs content (phase 3)
MANROFFOPT = "-c"
MANPAGER = "manpager"
FETCHER = "pfetch"
# TODO: maybe manually prepend?
TERMINFO_DIRS = "$XDG_DATA_HOME/terminfo:/opt/homebrew/share/terminfo:/usr/share/terminfo"
